# CI template for sbt projects. Should be extended for use.
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#extend-from-a-template
parameters:
  - name: jdk8Container
    default: 'duchessa/el8-jdk:8'
    type: string
  - name: jdk11Container
    default: 'duchessa/el8-jdk:11'
    type: string
  - name: publishContainer
    default: 'duchessa/el8-jdk:8'
    type: string
  - name: javaOptions
    default: '-Xmx4G -XX:MaxMetaspaceSize=1G'
    type: string
  - name: sbtBintrayVersion
    default: '0.5.6'
    type: string
  - name: publishOptionsVariableGroup
    default: ''
    type: string
  - name: bintrayOrganisation
    default: ''
    type: string
  - name: bintrayRepository
    default: ''

stages:
  - template: stages/integration_build-sbt.yml
    parameters:
      jdk8Container: ${{ parameters.jdk8Container }}
      jdk11Container: ${{ parameters.jdk11Container }}
      javaOptions: ${{ parameters.javaOptions }}
  - template: stages/publish_release-sbt-bintray.yml
    parameters:
      publishContainer: ${{ parameters.publishContainer }}
      javaOptions: ${{ parameters.javaOptions }}
      publishOptionsVariableGroup: ${{ parameters.publishOptionsVariableGroup }}
      sbtBintrayVersion: ${{ parameters.sbtBintrayVersion }}
      bintrayOrganisation: ${{ parameters.bintrayOrganisation }}
      bintrayRepository: ${{ parameters.bintrayRepository }}
